#!/usr/bin/env bash
#Transfers a file to server
scp -i ~/.ssh/ -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ~/holberton/holberton-system_engineering-devops/0x0C-web_server/some_page.html ubuntu@35.237.10.103:~/
