#!/usr/bin/env bash
#Installs nginx on server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | tee /var/www/html/index.html
service nginx restart
