#!/usr/bin/env bash
#Installs nginx and load balancer
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo apt-get -y install haproxy
echo "
frontend localnodes
    bind *:80
    mode http
    stats uri /haproxy?stats 
    default_backend nodes

backend nodes
    balance roundrobin
    server web-01 35.237.10.103:80 check
    server web-02 34.74.152.119:80 check " >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
