#!/usr/bin/env bash
#Installs nginx and load balancer
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get install haproxy
sudo echo "
frontend localnodes
    bind *:80
    mode http
    default_backend nodes

backend nodes
    mode http
    balance roundrobin
    server 1494-web-01 35.237.10.103:80 check
    server 1494-web-02 34.74.152.119:80 check " >> /etc/haproxy/haproxy.cfg
sudo service nginx restart
sudo service haproxy restart
