#!/usr/bin/env bash
# While loop to print string
i=0
while [ $i -le 100 ]
do
  if ! ((i % 15)); then
    echo "FizzBuzz"
  elif ! ((i % 5)); then
    echo "Buzz"
  elif ! ((i % 3)); then
    echo "Fizz"
  else
    echo $i
  fi
  ((i++))
done
