#!/usr/bin/env bash
# While loop to print string
i=0
while [ $i -le 9 ]
do
  if [[ "$i" == '3' ]]; then
    echo "bad luck"
  elif [[ "$i" == '7' ]]; then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  ((i++))
done
